spring.application.name=backend
spring.datasource.url=jdbc:postgresql://localhost:5432/recommendation_db
spring.datasource.username=postgres
spring.datasource.password=postgery123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true