name: Java Build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
          cache-dependency-path: 'backend/pom.xml'

      - name: Build with Maven
        working-directory: 'backend'
        run: mvn -B package
